import './globals.scss'

export const metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

import Header from '../components/header/Header.jsx'
import Footer from '../components/footer/Footer.jsx'
import logo from './layout_logo.png'
import Image from 'next/image'


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header/>
                {children}
                <Footer/>
                <Image type="image" className='layout_loo' src={logo} alt="logo" />
            </body>
        </html>
    )
}
